### ISSUE TITLE
Advance Google Analytics tracking

### ISSUE THREAD

**Issue by HonzaMikula** [HonzaMikula/kairly#130]
- [x] Subscribe / Unsubscribe newspapers
- [x] Subscribe / Unsubscribe authors
- [x] Start new edition / Update edition
- [x] Delete newspaper
- [x] Add to backlog / Remove to backlog
- [x] Expand issue
